# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f1e49e065f4a1547dff567c6489d3a750385ffc33fb2747d5756a83d17e688b4d58c46d773825c1b578faedc1cb6bd626582ada56b4bd5983323f6de20fed8c

test:
  secret_key_base: 7920e5df14608741d1f65cb8b4c4e799a74b37360e3c1b644841f02a166c30d057c67d389658bd251e4bd1723d35e5060f0cb4d50cc83136c429a2149d5483ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
